### PR TITLE
feat: created button component

### PR DESCRIPTION
**Pull request by JantuDeb**
### I have attached all the preview  bellow
image
image
image
image
image
image

### This pull request is for the button component

### CODE REVIEW

**Review by tushartiwari7 — APPROVED** [review]
All Buttons looks very nice and good use of utility classes.
Yes, You can merge this.

**Comment by sks-21** [comment]
The code looks good. Nice naming convention.

**Review by sks-21 — APPROVED** [review]
The code looks good. Nice naming convention.

**Comment by t007rushi** [comment]
Buttons Look Awesome, work on link Button.

**Pull request merged**
